services:
  playwright:
    stdin_open: true
    tty: true
    env_file: .env
    build:
      context: "../"
      dockerfile: "./e2e/Dockerfile"
      target: "playwright"
    volumes:
      - "./../__snapshots__:/e2e/__snapshots__"
      - "./../packages/foundations/build:/e2e/packages/foundations/build"
      - "./../packages/components/build:/e2e/packages/components/build"
      - "./../build-showcases:/e2e/build-showcases"
      - "./../showcases:/e2e/showcases"
      - "./../packages/react-core-components/playwright:/e2e/packages/react-core-components/playwright"
      - "./../packages/react-core-components/src:/e2e/packages/react-core-components/src"
      - "./../packages/v-core-components/src:/e2e/packages/v-core-components/src"
      - type: bind
        source: ./package.json
        target: /e2e/package.json
      - type: bind
        source: ./../packages/react-core-components/playwright.config.ts
        target: /e2e/packages/react-core-components/playwright.config.ts
      - type: bind
        source: ./../packages/v-core-components/playwright.config.ts
        target: /e2e/packages/v-core-components/playwright.config.ts
