---
name: Build Storybooks

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      storybook:
        required: true
        type: string
      baseUrl:
        required: true
        type: string

jobs:
  build-storybooks:
    name: Build Storybook ${{ inputs.storybook }}
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ‚è¨ Checkout repo
        uses: actions/checkout@v6

      - name: üîÑ Init Cache
        uses: ./.github/actions/npm-cache

      - name: ‚è¨ Download foundations build
        uses: actions/download-artifact@v7
        with:
          name: db-ux-foundations-build
          path: packages/foundations/build

      - name: ‚è¨ Download output
        uses: actions/download-artifact@v7
        with:
          name: db-ux-output
          path: output

      - name: ‚è¨ Download components build
        uses: actions/download-artifact@v7
        with:
          name: db-ux-components-build
          path: packages/components/build

      - name: ‚è´ Download stories
        if: ${{ inputs.storybook != 'composition-storybook' }}
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.storybook }}-stories
          path: storybooks/${{ inputs.storybook }}/src/components

      - name: üî® Build ${{ inputs.storybook }}
        env:
          ASSET_INIT_VECTOR: ${{ secrets.ASSET_INIT_VECTOR }}
          ASSET_PASSWORD: ${{ secrets.ASSET_PASSWORD }}
          BASE_URL: ${{ inputs.baseUrl }}
        run: |
          node node_modules/@db-ux/db-theme-fonts/build/scripts/index.js
          node node_modules/@db-ux/db-theme-icons/build/scripts/index.js
          npm run build --workspace=${{ inputs.storybook }}

      - name: ‚è´ Upload ${{ inputs.storybook }}
        uses: actions/upload-artifact@v6
        with:
          name: db-ux-${{ inputs.storybook }}
          path: build-storybooks/${{ inputs.storybook }}

      - name: üíÄ Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
