name: Lint & Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    strategy:
      fail-fast: false
      matrix:
        command: ["lint", "test"]
    steps:
      - name: â¬ï¸ Checkout repo
        uses: actions/checkout@v6

      - name: ğŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      # For now we keep this check in the codebase, even though that we already do the codespell check on git pre-commit hook. We might remove this check in the pipeline (even though that performance is not an issue, but it might be good for reducing external dependencies).
      - name: ğŸ“– Check spelling
        run: |
          npm run lint:codespell

      - name: âš¡ Run Lint
        if: ${{ matrix.command == 'lint' }}
        run: |
          pnpm --filter=nuxt-showcase run nuxt:prepare
          pnpm --filter=@db-ux/core-stylelint run build
          pnpm run lint

      - name: âš¡ Run Test
        if: ${{ matrix.command == 'test' }}
        run: pnpm run test
