name: Lint & Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    strategy:
      fail-fast: false
      matrix:
        command: ["lint", "test"]
    steps:
      - name: ‚è¨Ô∏è Checkout repo
        uses: actions/checkout@v6

      - name: üîÑ Init Cache
        uses: ./.github/actions/npm-cache

      # For now we keep this check in the codebase, even though that we already do the codespell check on git pre-commit hook. We might remove this check in the pipeline (even though that performance is not an issue, but it might be good for reducing external dependencies).
      - name: üìñ Check spelling
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .config/.codespellignorewords
          check_filenames: true

      - name: ‚ö° Run Lint
        if: ${{ matrix.command == 'lint' }}
        run: |
          npm run postinstall --workspace=nuxt-showcase
          npm run build --workspace=@db-ux/core-stylelint
          npm run lint

      - name: ‚ö° Run Test
        if: ${{ matrix.command == 'test' }}
        run: npm run test
