name: Lint & Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    strategy:
      fail-fast: false
      matrix:
        command: ["lint", "test", "codespell"]
    steps:
      - name: â¬ï¸ Checkout repo
        uses: actions/checkout@v6

      - name: ğŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      - name: ğŸ“– Check spelling
        if: ${{ matrix.command == 'codespell' }}
        run: |
          pnpm run lint:codespell

      - name: âš¡ Run Lint
        if: ${{ matrix.command == 'lint' }}
        run: |
          pnpm --filter=nuxt-showcase run nuxt:prepare
          pnpm --filter=@db-ux/core-stylelint run build
          pnpm run lint

      - name: âš¡ Run Test
        if: ${{ matrix.command == 'test' }}
        run: pnpm run test
