name: ğŸ’¡ğŸ  Lighthouse CI

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout repo
        uses: actions/checkout@v4

      - name: â¬ Download showcases
        uses: actions/download-artifact@v4
        with:
          name: db-ui-showcases
          path: build-showcases

      - name: ğŸ”ğŸ’¡ğŸ  Audit with Lighthouse
        id: audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: "./lighthouserc.json"
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: ğŸŒ³ğŸ‘ˆ Log links
        env:
          LINKS: ${{ steps.audit.outputs.links }}
        run: echo $LINKS
