name: ğŸ’¡ğŸ  Lighthouse CI

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout repo
        uses: actions/checkout@v4

      - name: â¬ Download showcases
        uses: actions/download-artifact@v4
        with:
          name: db-ui-showcases
          path: build-showcases

      # Lighthouse only searching for folders like dist/out/... see:
      # https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/cli/src/autorun/autorun.js#L68-L87
      - name: ğŸ’¡ğŸ ğŸ”¨ğŸ” Lighthouse workaround
        run: cp -r ./build-showcases/patternhub  ./build-showcases/dist

      - name: ğŸ”ğŸ’¡ğŸ  Audit with Lighthouse
        id: audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: "./lighthouserc.json"
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: ğŸŒ³ğŸ‘ˆ Log links
        env:
          LINKS: ${{ steps.audit.outputs.links }}
        run: echo $LINKS
