---
name: Vite Plugin Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test-vite-plugin:
    name: Test Vite Plugin
    runs-on: ubuntu-24.04
    steps:
      - name: â¬ Checkout repo
        uses: actions/checkout@v6

      - name: ğŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      - name: â¬ Download output
        uses: actions/download-artifact@v6
        with:
          name: db-ux-output
          path: output

      - name: â¬ Download vite-plugin build
        uses: actions/download-artifact@v6
        with:
          name: db-ux-vite-plugin-build
          path: packages/vite-plugin/build

      - name: ğŸ§ª Run Vite Plugin Tests
        run: npm run test --workspace @db-ux/core-vite-plugin
