---
name: PR review set
permissions:
  contents: read

on:
  pull_request_target:
    types: [review_requested]

jobs:
  auto-set-in-review:
    uses: ./.github/workflows/99-auto-set-in-review.yml
    secrets: inherit
